# Generated by Django 4.1 on 2022-08-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('changed_at', models.DateTimeField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Cuentas.cuenta')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
    ]
