# Generated by Django 4.1 on 2022-09-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tarjetas', '0002_remove_tarjeta_customer_id_tarjeta_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
