# Generated by Django 4.1 on 2022-09-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0003_remove_tarjeta_cliente_id_tarjeta_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarejeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_tarjeta',
            },
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipotarjeta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.tipotarejeta'),
        ),
    ]
