# Generated by Django 4.1 on 2022-09-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0004_tipotarejeta_tarjeta_tipotarjeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoTarejeta',
            new_name='TipoTarjeta',
        ),
    ]
