# Generated by Django 4.1 on 2022-09-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0005_alter_sucursal_table'),
        ('Prestamos', '0002_alter_tipoprestamo_nombre_prestamo_montomax'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='sucursal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sucursales.sucursal'),
        ),
    ]
