# Generated by Django 4.1 on 2022-09-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_prestamo_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='cliente',
            new_name='user_id',
        ),
    ]
