# Generated by Django 4.1 on 2022-08-30 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'TIPO_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('customer_dni', models.PositiveIntegerField(db_column='customer_DNI')),
                ('dob', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(null=True)),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipocliente')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
    ]
