# Generated by Django 4.1 on 2022-08-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='tipocliente',
            table='tipo_cliente',
        ),
    ]
