# Generated by Django 4.1 on 2022-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigopostal', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
