# Generated by Django 4.1 on 2022-09-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0002_sucursales_delete_sucursal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursales',
            new_name='Sucursal',
        ),
    ]
