# Generated by Django 4.1 on 2022-09-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0003_rename_sucursales_sucursal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
    ]
