# Generated by Django 4.1 on 2022-09-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0004_alter_sucursal_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursales',
        ),
    ]
